export SELECT_QUIZ = 'SELECT_QUIZ';

export NEXT_ANSWER = 'NEXT_ANSWER';

export SUBMIT_ANSWER = 'SUBMIT_ANSWER';

export CREATE_NEW_USER = 'CREATE_NEW_USER';

export LOGIN_USER = 'LOGIN_USER';

export TOGGLE_LOGIN_REGISTER = 'TOGGLE_LOGIN_REGISTER';

export GRANT_ACCESS = 'GRANT_ACCESS';
